export class Order  {
	
	constructor(		
	public id:number,
	public assigned_to:any,
	public cc_number:any,
	public comuna: string,
	public create_at:any,	
	public create_by :any,
	public customer_id :number,
	public datos: any,
	public direccion: string,
	public estatus: string,
	public status_id: number,
	public imagen: any,	
	public important:any,
	public leido_por: any,
	public medidor: any,
	public order_number:any,
	public observation:string,
	public order_date:any,
	public provincia: string,
	public required_date:any,
	public service_id :number,
	public servicetype_id :number,	
	public servicetype:string,
	public status:any,
	public user:string,
	public userassigned: string,
	public update_at:any,
	public userupdate: string,
	public vencimiento_date:any,
	public orderatributofirma: any,
	public atributo_firma:any
	){}
}
