export class Service  {
	
	constructor(	
	public id:number,
	public accept_edpdate: any,
	public address: any,
	public area_solicitante: any,
	public assigned_date_touser1: any,
	public assigned_date_touser2: any,
	public category_id:number,
	public checked_crodate: any,
	public cc_number:any,
	public comuna_id:number,
	public contratista: any,
	public contract_number: any,
	public cro_number: any,
	public cro_status: any,
	public create_by: any,
	public description: any,
	public due_date: any,
	public ejecutivo: any,
	public edp_amount: any,
	public edp_number: any,
	public edp_status: any,
	public gestor: any,
	public gom_number:any,
	public length: any,
	public mo_number: any,
	public name:any,
	public observation: any,
	public other_observation: any,
	public order_number:any,
	public other_ito_civil: any,
	public other_ito_electrico: any,
	public other_assigned_date_toitocivil: any,
	public other_assigned_date_toitoelec: any,
	public project: any,
	public project_id:number,
	public provincia_id:number,
	public reject_edpdate: any,
	public region_id:number,
	public responsable_obra: any,
	public responsable_phone: any,
	public responsable_email:any,
	public responsable_unidad:any,
	public responsable_unidad_phone: any,
	public responsable_unidad_email: any,
	public reception_date: any,
	public reception_crodate: any,
	public required_date: any,
	public send_edpdate: any,
	public service_id: any,
	public service_name:any,	
	public status:number,
	public update_by: any,
	public user_informador: any,
	public user_responsable:any,
	public user_itocivil_assigned_to: any,
	public user_itoelec_assigned_to: any,
	public type_id:number,		
	public unidad_responsable: any,
	public create_at:any,	
	public update_at:any
	){}
}