export { AddDocComponent } from './dialog/add-doc/add-doc.component';
export { AddTeamComponent } from 'src/app/pages/team/dialog/add-team/add-team.component';
// export { DropdownNotificationComponent } from './dropdown-notification/dropdown-notification.component';
export { EditServiceComponent } from './dialog/editservice/editservice.component';
export { FilelistComponent } from '../../components/dialog/filelist/filelist.component';
export { FileListComponent } from '../../components/file-list/file-list.component';
export { FileUploadComponent } from '../../components/file-upload/file-upload.component';
export { FooterComponent } from './footer/footer.component';
export { KpiComponent } from './firebase/kpi/kpi.component';
export { KpiProjectComponent } from './kpi/kpi-project.component';
export { KpiProjectAmchartsComponent } from './kpi/kpi-project-amcharts/kpi-project-amcharts.component';
export { KpiProjectForecastComponent } from './kpi/kpi-project-forecast/kpi-project-forecast.component';
export { KpiProjectDetailComponent } from './kpi/kpi-project-detail/kpi-project-detail.component';
export { KpiProjectHeatdayComponent } from './kpi/kpi-project-heatday/kpi-project-heatday.component';
export { KpiProjectHeatmapComponent } from './kpi/kpi-project-heatmap/kpi-project-heatmap.component';
export { KpiProjectLocationComponent } from './kpi/kpi-project-location/kpi-project-location.component';
export { LoadingComponent } from './loading/loading.component';
// export { MenuComponent } from './menu/menu.component';
export { MynavComponent } from './mynav/mynav.component';
// export { NotfoundComponent } from './notfound/notfound.component';
export { ProgressSpinnerComponent } from './progress-spinner/progress-spinner.component';
export { ReportkpiComponent } from './firebase/reportkpi/reportkpi.component';
export { ShowComponent } from 'src/app/components/dialog/show/show.component';
export { TagUserComponent } from './taguser/taguser.component';
export { TagUserDbComponent } from './tag-user-db/tag-user-db.component';
export { TagUserMatSelectComponent } from './tag-user-mat-select/tag-user-mat-select.component';
export { UploaderComponent  } from './uploader/uploader.component';
export { UploadTaskComponent } from './upload-task/upload-task.component';
export { UserJobProfileComponent } from 'src/app/components/dialog/user-job-profile/user-job-profile.component';
export { ViewOrderTimeSpentComponent } from '../../components/views/viewordertimespent/viewordertimespent.component';
